import FWCore.ParameterSet.Config as cms

pythiaUESettingsBlock = cms.PSet(
	pythiaUESettings = cms.vstring(
'MSTU(21)=1     ! Check on possible errors during program execution', 
            'MSTJ(22)=2     ! Decay those unstable particles', 
            'PARJ(71)=10 .  ! for which ctau  10 mm', 
            'MSTP(33)=0     ! no K factors in hard cross sections', 
            'MSTP(2)=1      ! which order running alphaS', 
            'MSTP(51)=10042 ! structure function chosen (external PDF CTEQ6L1)', 
            'MSTP(52)=2     ! work with LHAPDF', 
            'PARP(62)=1.13 ! ISR cutoff', 
            'PARP(64)=0.68 ! ISR renormalization scale prefactor ', 
            'PARP(67)=1.00 !   ISR Q2max factor',
            'PARP(72)=0.53 ! LambdaQCD for FSR', 
            'PARP(77)=0.357 ! CR', 
            'PARP(78)=0.235 ! CR', 
            'PARP(82)=2.34 ! UE IR cutoff at reference ecm ', 
            'PARP(83)=0.356 !   UE mass distribution parameter ',
            'PARP(84)=0.605 !  UE mass distribution parameter ',
            'PARP(90)=0.246 !  UE IR cutoff ecm scaling power  ',
#AMBT1
            'MSTP( 3) =  2   ! INT switch for choice of LambdaQCD',
            'MSTP(64) =  2   ! ISR alphaS type',
            'MSTP(67) =  2   ! ISR coherence option for 1st emission',
            'MSTP(68) =  3   ! ISR phase space choice & ME corrections',
            'MSTP(70) =  0   ! ISR IR regularization scheme',
            'MSTP(72) =  1   ! IFSR scheme for non-decay FSR ',
            'PARP(71) =  4.00 !   IFSR Q2max factor in non-s-channel procs ',
            'PARJ(81) =  0.29 !   FSR LambdaQCD (inside resonance decays)',
            'PARJ(82) =  1.00 !   FSR IR cutoff               ',
            'MSTP(33) =  0   ! switch for K-factor on/off & type',
            'MSTP(81) =  21  ! UE model                             ',
            'MSTP(82) =  4   ! UE hadron transverse mass distribution',
            'MSTP(88) =  1   ! BR composite scheme            ',
            'MSTP(89) =  1   ! BR color scheme                ',
            'PARP(79) =  2.00 !   BR composite x enhancement     ',
            'PARP(80) =  0.10 !   BR breakup suppression         ',
            'MSTP(91) =  1   ! BR primordial kT distribution ',
            'PARP(91) =  2.00 !   BR primordial kT width <|kT|>  ',
            'PARP(93)=10.0  ! BR primordial kT UV cutoff', 
            'MSTP(95) =  6   ! FSI color (re-)connection model',
            'PARP(78) =  0.538 !   FSI color reconnection strength ',
            'PARP(77) =  1.016 !   FSI color reco high-pT damping strength ',
            'MSTJ(11) =  4  ! HAD choice of fragmentation function(s)',
            'PARJ(1) = 0.08 ! HAD diquark suppression',
            'PARJ(2) = 0.21 ! HAD strangeness suppression',
            'PARJ(3) = 0.94 ! HAD strange diquark suppression',
            'PARJ(4) = 0.04 ! HAD vector diquark suppression',
            'PARJ(5) = 0.50 !   HAD P(popcorn) ',
            'PARJ(6) = 0.50 !   HAD extra popcorn B(s)-M-B(s) supp',
            'PARJ(7) = 0.50 !   HAD extra popcorn B-M(s)-B supp ',
            'PARJ(11) = 0.35 ! HAD P(vector meson), u and d only',
            'PARJ(12) = 0.35 ! HAD P(vector meson) contains ',
            'PARJ(13) = 0.54 ! HAD P(vector meson), heavy quarks',
            'PARJ(21) = 0.34 ! HAD fragmentation pt',
            'PARJ(25) = 0.63 ! HAD eta0 suppression',
            'PARJ(26) = 0.12 ! HAD eta0 suppression',
            'PARJ(41) = 0.30 !  HAD string parameter a(Meson)',
            'PARJ(42) = 0.58 !  HAD string parameter b ',
            'PARJ(45) = 0.50 !  HAD string a(Baryon)-a(Meson)',
            'PARJ(46) = 1.00 !  HAD Lund(=0)-Bowler(=1) rQ (rc) '
        )
)
