import FWCore.ParameterSet.Config as cms

pythiaUESettingsBlock = cms.PSet(
	pythiaUESettings = cms.vstring(
'MSTU(21)=1     ! Check on possible errors during program execution', 
            'MSTJ(22)=2     ! Decay those unstable particles', 
            'PARJ(71)=10 .  ! for which ctau  10 mm', 
            'MSTP(33)=0     ! no K factors in hard cross sections', 
            'MSTP(2)=1      ! which order running alphaS', 
            'MSTP(51)=10042 ! structure function chosen (external PDF CTEQ6L1)', 
            'MSTP(52)=2     ! work with LHAPDF', 
            'MSTP(3)=1      ! INT switch for choice of LambdaQCD         ',
            'MSTU(112)=5    ! INT n(flavors) for LambdaQCD               ',
            'PARU(112)=0.1920 !   INT LambdaQCD                              ',
            'PARP(1)=0.1920 !  ME/UE LambdaQCD                            ',
            'PARJ(81)=0.2560!   FSR LambdaQCD (inside resonance decays)    ',
            'PARP(72)=0.5270!   IFSR LambdaQCD (outside resonance decays   ',
            'PARP(61)=0.1920!  ISR LambdaQCD                              ',
            'MSTP(64)=2     ! ISR alphaS type                            ',
            'PARP(64)=0.6800!   ISR renormalization scale prefactor        ',
            'MSTP(67)=2     ! ISR coherence option for 1st emission      ',
            'PARP(67)=1.0000!   ISR Q2max factor                           ',
            'MSTP(68)=3     ! ISR phase space choice & ME corrections    ',
            'MSTP(70)=0     ! ISR IR regularization scheme               ',
            'PARP(62)=1.1300!    ISR IR cutoff                              ',
            'MSTP(72)=2     ! IFSR scheme for non-decay FSR              ',
            'PARP(71)=4.0000!   IFSR Q2max factor in non-s-channel procs   ',
            'PARP(72)=0.5270!   IFSR LambdaQCD (outside resonance decays   ',
            'PARJ(82)=0.8300!   FSR IR cutoff                              ',
            'MSTP(33)=0     ! "K" switch for K-factor on/off & type      ',
            'MSTP(81)=21    ! UE model                                   ',
            'PARP(82)=2.3400!   UE IR cutoff at reference ecm              ',
            'PARP(89)=1800.0!   UE IR cutoff reference ecm                 ',
            'PARP(90)=0.2460!   UE IR cutoff ecm scaling power             ',
            'MSTP(82)=4     !  UE hadron transverse mass distribution     ',
            'PARP(83)=0.3560!   UE mass distribution parameter             ',
            'PARP(84)=0.6050!   UE mass distribution parameter             ',
            'PARP(87)=0.7000!   UE qq enhancement at low pT                ',
            'PARP(88)=0.5000!   UE qq enh scale / pT0                      ',
            'MSTP(88)=1     ! BR composite scheme                        ',
            'MSTP(89)=1     ! BR color scheme                            ',
            'PARP(79)=2.0000!   BR composite x enhancement                 ',
            'PARP(80)=0.1000!   BR breakup suppression                     ',
            'MSTP(91)=1     ! BR primordial kT distribution              ',
            'PARP(91)=2.0000!    BR primordial kT width <|kT|>              ',
            'PARP(93)=10.000!    BR primordial kT UV cutoff                 ',
            'MSTP(95)=6     !  FSI color (re-)connection model            ',
            'PARP(78)=0.2350!   FSI color reconnection strength            ',
            'PARP(77)=0.3570!   FSI color reco high-pT damping strength    ',
            'MSTJ(11)=5     ! HAD choice of fragmentation function(s)    ',
            'PARJ( 1)=0.0730!   HAD diquark suppression                    ',
            'PARJ( 2)=0.2020!   HAD strangeness suppression                ',
            'PARJ( 3)=0.9500!   HAD strange diquark suppression            ',
            'PARJ( 4)=0.0330!   HAD vector diquark suppression             ',
            'PARJ( 5)=0.5000!   HAD P(popcorn)                             ',
            'PARJ( 6)=0.5000!   HAD extra popcorn B(s)-M-B(s) supp         ',
            'PARJ( 7)=0.5000!   HAD extra popcorn B-M(s)-B supp            ',
            'PARJ(11)=0.3090!   HAD P(vector meson), u and d only          ',
            'PARJ(12)=0.4020!   HAD P(vector meson), contains s            ',
            'PARJ(13)=0.5440!   HAD P(vector meson), heavy quarks          ',
            'PARJ(14)=0.0000!   HAD P(L=1;S=0,J=1)                         ',
            'PARJ(15)=0.0000!   HAD P(L=1;S=1,J=0)                         ',
            'PARJ(16)=0.0000!   HAD P(L=1;S=1,J=1)                         ',
            'PARJ(17)=0.0000!   HAD P(L=1;S=1,J=2)                         ',
            'PARJ(18)=1.0000!   HAD extra spin-3/2 baryon supp             ',
            'PARJ(19)=1.0000!   HAD extra leading-baryon supp              ',
            'PARJ(21)=0.3000!   HAD fragmentation pT                       ',
            'PARJ(25)=0.6280!   HAD eta0 suppression                       ',
            'PARJ(26)=0.1290!   HAD eta0prime suppression                      ',
            'PARJ(41)=0.3680!   HAD string parameter a(Meson)              ',
            'PARJ(42)=1.0040!   HAD string parameter b                     ',
            'PARJ(45)=0.5000!   HAD string a(Baryon)-a(Meson)              ',
            'PARJ(46)=1.0000!   HAD Lund(=0)-Bowler(=1) rQ (rc)            ',
            'PARJ(47)=0.8730!   HAD Lund(=0)-Bowler(=1) rb                 '
                )
        )
)
